server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Test123
#  datasource:
#    url: ${db_url}
#    username:  ${db_user}
#    password:  ${db_pass}
#    driverClassName: org.h2.Driver
#    console.enabled: true
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true